workflows:
  android_studio_benchmark_linux_x2:
    name: Android Studio Benchmark on Linux_x2
    instance_type: linux_x2
    max_build_duration: 90 # in minutes, adjust as needed
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        api_level: 33                 # Match compileSdkVersion
        build_tools_version: '30.0.3' # Matching your gradle config
        jdk: openjdk17
    scripts:
      - name: Install required SDK components
        script: |
          echo "Installing required Android SDK components..."
          yes | sdkmanager "platforms;android-33" "platform-tools" "build-tools;30.0.3"
          sdkmanager --licenses || true
      - name: Clean previous build
        script: ./gradlew clean
      - name: Build 1/3
        script: ./gradlew assembleDebug #--stacktrace --info --debug --refresh-dependencies
      #- name: Build 2/3
      #  script: ./gradlew assembleDebug
      #- name: Build 3/3
      #  script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk

  android_studio_benchmark_linux_x4:
    name: Android Studio Benchmark on Linux_x4
    instance_type: linux_x4
    max_build_duration: 90 # in minutes, adjust as needed
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        api_level: 33                 # Match compileSdkVersion
        build_tools_version: '30.0.3' # Matching your gradle config
        jdk: openjdk17
    scripts:
      - name: Install required SDK components
        script: |
          echo "Installing required Android SDK components..."
          yes | sdkmanager "platforms;android-33" "platform-tools" "build-tools;30.0.3"
          sdkmanager --licenses || true
      - name: Clean previous build
        script: ./gradlew clean
      - name: Build 1/3
        script: ./gradlew assembleDebug --stacktrace --info --debug --refresh-dependencies
      - name: Build 2/3
        script: ./gradlew assembleDebug
      - name: Build 3/3
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
